---
apiVersion: "extensions/v1beta1"
kind: "Deployment" 
spec: 
  replicas: 1
  template: 
    spec: 
      containers: 
      - env:
         - name: JAVA_OPTIONS
           value: -Xms32m -Xmx32m -Xss256k -XX:MaxDirectMemorySize=64m -XX:+UseCGroupLimits
        resources: 
          limits: 
            memory: "250Mi"