---
apiVersion: "extensions/v1beta1"
kind: "Deployment" 
spec: 
  replicas: 1
  template: 
    spec: 
      containers: 
      - env:
         - name: JAVA_OPTIONS
           value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:ThreadStackSize=256k -Dspring.profiles.active=openshift
         - name: AB_JOLOKIA_OFF
           value: "true"
         - name: AB_OFF
           value: "true"