---
apiVersion: "extensions/v1beta1"
kind: "Deployment" 
spec: 
  replicas: 1
  template: 
    spec: 
      containers: 
      - env:
         - name: JAVA_OPTIONS
           value: -Xms32m -Xmx32m -Xss256k -Dspring.profiles.active=openshift -XX:MaxRAM=157286400
         - name: AB_JOLOKIA_OFF
           value: "true"
         - name: AB_OFF
           value: "true"